import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
const arsenal_SC = localFont({
	src: [
		{ path: './fonts/Arsenal_SC/ArsenalSC-Regular.ttf', weight: '400' },
		{ path: './fonts/Arsenal_SC/ArsenalSC-Bold.ttf', weight: '700' },
		{ path: './fonts/Arsenal_SC/ArsenalSC-Italic.ttf', weight: '400', style: 'italic' },
		{ path: './fonts/Arsenal_SC/ArsenalSC-BoldItalic.ttf', weight: '700', style: 'italic' },
	],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${arsenal_SC.className} antialiased bg-background`}>{children}</body>
		</html>
	)
}
