import type { Metadata } from 'next'
import './styles/globals.css'
import Logo from '@/app/icons/logo.svg'
import { Montserrat, Unbounded } from 'next/font/google'

const montserrat = Montserrat({
	subsets: ['cyrillic', 'cyrillic-ext'],
})

const unbounded = Unbounded({
	subsets: ['cyrillic', 'cyrillic-ext', 'latin'],
	variable: '--font-unbounded-next',
})

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${montserrat} ${unbounded.className} antialiased bg-background px-4`}>
				<div className="pt-7 flex flex-col items-center">
					<Logo className="w-fit" />
				</div>
				{children}
			</body>
		</html>
	)
}
